# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         jsFind
version:      0.04
version_from: jsFind.pm
installdirs:  site
requires:
    Carp:                          0
    File::Path:                    0
    HTML::Entities:                0
    POSIX:                         0
    Text::Iconv:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
